version: '2.18.1'
services:
  server:
    build: ./server
    container_name: server_container
    ports:
      - '3000:3000'
    volumes:
      - ./server:/app
      - /app/node_modules
  client:
    build: ./client
    container_name: client_container
    ports:
      - '4200:4200'
    volumes:
      - ./client:/app
      - /app/node_modules