version: '2.18.1'
services:

  # DATABSE SERVICE
  database:
    image: postgres:13
    container_name: database_container
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password1234
      POSTGRES_DB: compo_search_database
    ports:
      - 5432:5432
    volumes:
      - ./server/src/config/populate-db.sql:/docker-entrypoint-initdb.d/populate-db.sql

  # SERVER SERVICE 
  server:
    build: ./server
    depends_on:
      - database
    container_name: server_container
    ports:
      - '3000:3000'
    volumes:
      - ./server:/app
      - /app/node_modules

  # CLIENT SERVICE
  client:
    build: ./client
    container_name: client_container
    ports:
      - '4200:4200'
    volumes:
      - ./client:/app
      - /app/node_modules
      
  # PGADMIN SERVICE
  pgadmin:
    image: dpage/pgadmin4
    environment:
            PGADMIN_DEFAULT_EMAIL: "admin@example.com"
            PGADMIN_DEFAULT_PASSWORD: "password123"
    ports:
        - "16543:80"
    depends_on:
        - database