#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Lint and format the server directory
cd server
npm run lint-server

# Lint and format the client directory
# For now this script is only formating the client.
cd ../client 
npm run lint-client
