name: Testing client (E2E)

on:
  push:
    branches:
      - build/ci-testing
    # paths:
    #   - "client/**"

jobs:
  tests_e2e:
    name: Run end-to-end tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v3
      # - uses: actions/setup-node@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          # run_install: |
          #   - recursive: true
          #     args: [--frozen-lockfile, --strict-peer-dependencies]
          #   - args: [--global, gulp, prettier, typescript]
      - name: Install dependencies
        # run: pnpm ci
        run: pnpm install --frozen-lockfile --only=production --ignore-scripts
      - name: Install playwright browsers
        run: pnpx playwright install --with-deps
      - name: Fix install issues of @playwright/test (1)
        run: pnpm rm playwright/test
      - name: Fix install issues of @playwright/test (2)
        run: pnpm add -D @playwright/test
      - name: Run tests
        run: pnpx playwright test

